name: stoker
description: "Sistema de Gestão de Inventário para Estúdios de Produção"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.0.1
  supabase_flutter: ^2.9.1
  intl: ^0.19.0
  printing: ^5.14.2
  pdf: ^3.11.3
  collection: ^1.19.1
  image_picker: ^1.1.2
  equatable: ^2.0.5 
  mask_text_input_formatter: ^2.9.0
  flutter_speed_dial: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true